blank_issues_enabled: true
contact_links:
  - name: Want to see new content? Open a discussion!
    url: https://github.com/dbt-athena/dbt-athena.github.io/discussions/new
    about: You can open a discussion to propose new content for the dbt-athena documentation.
  - name: Have questions about dbt or dbt-athena? Join the Community!
    url: https://www.getdbt.com/community/join-the-community
    about: You can join the dbt Labs Community to ask and answer questions (#db-athena channel).
